import React from 'react';
import { Link } from 'react-router-dom';
import { LegalPage } from './LegalPage';

const UPDATED = '19 August 2026';

/**
 * Transparency disclosure for the EU AI Act, Article 50, which has applied since
 * 2 August 2026.
 *
 * Every claim here describes behaviour that already exists — the marker is added
 * server-side in tools/biography.py on the formatter's single return path. If the
 * marking changes, this page changes with it.
 */
const AiTransparencyPage = () => (
  <LegalPage title="AI Transparency" updated={UPDATED} path="/ai-transparency">
    <p>
      <strong>Lineage Nexus is an AI system.</strong> When you ask it something, you are
      interacting with software, not a person, and no human reviews its answers before you
      see them. This page explains what that means for the research it produces.
    </p>

    <h2>What the AI actually does</h2>
    <p>
      Two different things happen in one conversation, and the distinction matters:
    </p>
    <ul>
      <li>
        <strong>Searching is not generated.</strong> Records come from real archives —
        Open Archieven, WikiTree and others listed on our{' '}
        <Link to="/sources">Sources</Link> page. Those are retrieved, not invented.
      </li>
      <li>
        <strong>Biographies are generated.</strong> The prose, the ordering, the phrasing
        and the conclusions drawn from those records are written by a language model
        (Google Gemini). This is synthetic text.
      </li>
    </ul>
    <p>
      So a biography is an AI-written interpretation of real records. The records may be
      sound while the interpretation is wrong.
    </p>

    <h2>How generated text is marked</h2>
    <p>
      Every biography the system produces carries a machine-readable marker as its first
      line, in an HTML comment:
    </p>
    <p>
      <code>
        &lt;!-- AI_GENERATED: &#123;"generator":"Lineage Nexus","model":"…",
        "generatedAt":"…","disclosure":"https://lineage.nexus/ai-transparency"&#125; --&gt;
      </code>
    </p>
    <p>
      It is added by our server on the one path every biography passes through, rather than
      being requested of the model, so it cannot be omitted by chance. It survives copying
      and pasting, and travels with the text when you publish it — including into a WikiTree
      profile, where it stays readable in the source but does not display on the page.
    </p>
    <p>
      <strong>Please leave it in place.</strong> It is what allows anyone reading that
      profile later — including you — to tell that the wording was drafted by a machine.
    </p>

    <h2>What can go wrong</h2>
    <p>
      Language models produce fluent text regardless of whether it is correct, which makes
      their mistakes harder to notice than a human's would be. In genealogy specifically,
      expect:
    </p>
    <ul>
      <li>Two similarly named people in the same parish merged into one.</li>
      <li>Dates or places transposed between relatives, or between records.</li>
      <li>Relationships asserted more confidently than the records support.</li>
      <li>Plausible detail that is not in any cited source.</li>
    </ul>
    <p>
      This is why every biography includes citations: they are there to be checked, not
      merely displayed. <strong>Verify against the cited records before publishing anything
      to a shared family tree.</strong> A mistake published to WikiTree becomes other
      people's research.
    </p>

    <h2>You stay in control</h2>
    <p>
      Nothing is published automatically. The system drafts; you read, correct and decide
      whether to use it. The browser extension fills in a form for you to review — it never
      submits one.
    </p>

    <h2>Which model, and who provides it</h2>
    <p>
      Text is generated by Google's Gemini models, called with your own API key. Google is
      the provider of the underlying model; we are the provider of this system built on it.
      The specific model used for each biography is recorded in the marker above, so you can
      tell later what produced a given piece of text.
    </p>

    <h2>Regulatory basis</h2>
    <p>
      This page exists to meet the transparency obligations in <strong>Article 50 of the EU
      AI Act</strong>, which have applied since 2 August 2026: informing you that you are
      interacting with an AI system, and marking synthetic text in a machine-readable form
      so it is detectable as artificially generated.
    </p>
    <p>
      If you believe our marking or disclosure falls short, please tell us — we would rather
      hear it from you than not know.
    </p>

    <h2>Related</h2>
    <p>
      See <Link to="/sources">Sources</Link> for the archives searched,{' '}
      <Link to="/privacy">Privacy</Link> for what is stored and what is not, and{' '}
      <Link to="/terms">Terms of Use</Link> for the verify-before-publishing expectation.
    </p>
  </LegalPage>
);

export default AiTransparencyPage;
