import React, { useState, useEffect } from 'react';
import { User, Network, Check, Copy, History, Sparkles, AlertCircle, RotateCcw, ChevronDown } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const INITIAL_VISIBLE_COUNT = 15;
const PAGE_INCREMENT = 15;

const formatDateToISO = (str) => {
  if (!str) return str;
  const s = str.trim();
  if (/^\d{4}-\d{2}(-\d{2})?$/.test(s)) return s;
  
  const isBefore = /\bbefore\b|\bbef\b/i.test(s);
  const isAfter = /\bafter\b|\baft\b/i.test(s);
  const isEstimate = /\babout\b|\babt\b|\best\b|\bestimated\b|\bcirca\b/i.test(s);

  const clean = s.replace(/^(before|bef|after|aft|about|abt|est|estimated|circa|c\.)\s+/i, '').trim();

  const months = {
    january: '01', feb: '02', february: '02', mar: '03', march: '03', apr: '04', april: '04',
    may: '05', jun: '06', june: '06', jul: '07', july: '07', aug: '08', august: '08',
    sep: '09', september: '09', oct: '10', october: '10', nov: '11', november: '11', dec: '12', december: '12',
    jan: '01', februari: '02', maart: '03', mei: '05', juni: '06', juli: '07', augustus: '08', oktober: '10'
  };

  const m1 = clean.match(/^([A-Za-z]+)\s+(\d{1,2}),?\s+(\d{4})$/);
  if (m1 && months[m1[1].toLowerCase()]) {
    const mm = months[m1[1].toLowerCase()];
    const dd = m1[2].padStart(2, '0');
    const iso = `${m1[3]}-${mm}-${dd}`;
    return isBefore ? `before ${iso}` : isAfter ? `after ${iso}` : isEstimate ? `about ${iso}` : iso;
  }

  const m2 = clean.match(/^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$/);
  if (m2 && months[m2[2].toLowerCase()]) {
    const mm = months[m2[2].toLowerCase()];
    const dd = m2[1].padStart(2, '0');
    const iso = `${m2[3]}-${mm}-${dd}`;
    return isBefore ? `before ${iso}` : isAfter ? `after ${iso}` : isEstimate ? `about ${iso}` : iso;
  }

  const m3 = clean.match(/^([A-Za-z]+)\s+(\d{4})$/);
  if (m3 && months[m3[1].toLowerCase()]) {
    const mm = months[m3[1].toLowerCase()];
    const iso = `${m3[2]}-${mm}`;
    return isBefore ? `before ${iso}` : isAfter ? `after ${iso}` : isEstimate ? `about ${iso}` : iso;
  }

  return s;
};

const sanitizeDutchNamePrefixes = (vitals) => {
  if (!vitals) return vitals;
  const dutchPrefixes = ['van', 'de', 'den', 'der', 'van de', 'van den', 'van der', 'ten', 'ter', 'te', 'in \'t', 'op \'t', 'van \'t', 'vander', 'vanden', 'du', 'la', 'le', 'von'];
  
  if (vitals.firstName) {
    const fnParts = vitals.firstName.trim().split(/\s+/);
    if (fnParts.length >= 2) {
      let prefixToMove = '';
      const lastTwo = `${fnParts[fnParts.length - 2]} ${fnParts[fnParts.length - 1]}`.toLowerCase();
      if (dutchPrefixes.includes(lastTwo)) {
        prefixToMove = fnParts.slice(-2).join(' ');
        vitals.firstName = fnParts.slice(0, -2).join(' ');
      } else {
        const lastOne = fnParts[fnParts.length - 1].toLowerCase();
        if (dutchPrefixes.includes(lastOne)) {
          prefixToMove = fnParts[fnParts.length - 1];
          vitals.firstName = fnParts.slice(0, -1).join(' ');
        }
      }

      if (prefixToMove) {
        const currentLastName = vitals.lastNameAtBirth || '';
        if (!currentLastName.toLowerCase().startsWith(prefixToMove.toLowerCase())) {
          vitals.lastNameAtBirth = `${prefixToMove} ${currentLastName}`.trim();
        }
      }
    }
  }

  // If lastNameCurrent was set equal to (or un-prefixed version of) lastNameAtBirth, delete it so the optional field remains blank
  if (vitals.lastNameCurrent && vitals.lastNameAtBirth) {
    const cleanCurrent = vitals.lastNameCurrent.trim().toLowerCase();
    const cleanBirth = vitals.lastNameAtBirth.trim().toLowerCase();
    if (cleanCurrent === cleanBirth || cleanBirth.endsWith(` ${cleanCurrent}`) || cleanBirth.endsWith(`'${cleanCurrent}`)) {
      delete vitals.lastNameCurrent;
    }
  }

  return vitals;
};

const CodeBlock = ({ node, inline, className, children, ...props }) => {
  const [copied, setCopied] = useState(false);
  const [pushed, setPushed] = useState(false);
  const match = /language-(\w+)/.exec(className || '');
  const content = String(children).replace(/\n$/, '');

  const handlePushExtension = () => {
    let vitals = {};
    const text = content;

    // 1. Prioritize reading structured JSON comment generated by backend model
    const jsonCommentMatch = text.match(/<!--\s*LINEAGE_NEXUS_DATA:\s*({[\s\S]+?})\s*-->/);
    if (jsonCommentMatch) {
      try {
        vitals = JSON.parse(jsonCommentMatch[1]);
      } catch (err) {
        console.warn('Failed to parse LINEAGE_NEXUS_DATA comment:', err);
      }
    }

    // 2. Fallback regex parsing if JSON comment is missing any fields
    if (!vitals.firstName) {
      const nameMatch = text.match(/'''([^']+)'''/);
      if (nameMatch) {
        const fullName = nameMatch[1].trim();
        const nameParts = fullName.split(' ');
        if (nameParts.length > 1) {
          vitals.firstName = nameParts.slice(0, -1).join(' ');
          vitals.lastNameAtBirth = nameParts[nameParts.length - 1];
        } else {
          vitals.firstName = fullName;
        }
      }
    }

    if (!vitals.birthDate) {
      const birthMatch = text.match(/was born\s+((?:on|in|about|abt|circa|c\.|est|estimated)?\s*(?:[A-Za-z]+\s+\d+,\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+[A-Za-z]+\s+\d{4}|[A-Za-z]+\s+\d{4}|\d{4}))(?:,\s+in\s+([^\n.]+?))?(?:,\s*(?:the\s+)?(?:son|daughter)\s+of|\.|$|<)/i) ||
                         text.match(/Birth Date:\s*([^\n]+)/i);
      if (birthMatch) {
        vitals.birthDate = formatDateToISO(birthMatch[1]);
        if (birthMatch[2] && !vitals.birthLocation) {
          vitals.birthLocation = birthMatch[2]
            .replace(/,?\s*(?:the\s+)?(?:son|daughter)\s+of[\s\S]*/i, '')
            .replace(/,?\s*\[\[[\s\S]*/, '')
            .replace(/\.$/, '')
            .trim();
        }
      }
    }

    if (!vitals.deathDate) {
      const deathMatch = text.match(/(?:passed away|died)\s+((?:before|after|about|abt|est|circa)?\s*(?:[A-Za-z]+\s+\d+,\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+[A-Za-z]+\s+\d{4}|[A-Za-z]+\s+\d{4}|\d{4}))(?:,\s+in\s+([^\n.<]+?))?(?:,|\.|$|<)/i) ||
                         text.match(/(?:passed away|died)\s+in\s+([^\n.<]+?)\s+on\s+([A-Za-z]+\s+\d+,\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+[A-Za-z]+\s+\d{4})/i) ||
                         text.match(/Death Date:\s*([^\n]+)/i);
      if (deathMatch) {
        vitals.deathDate = formatDateToISO(deathMatch[1]);
        if (deathMatch[2] && !vitals.deathLocation) {
          vitals.deathLocation = deathMatch[2].replace(/\.$/, '').trim();
        }
      }
    }

    if (!vitals.gender) {
      if (/was born[^\n]*\bthe son of\b/i.test(text) || /\bHe married\b/i.test(text) || /^\s*Gender:\s*Male/im.test(text)) {
        vitals.gender = 'Male';
      } else if (/was born[^\n]*\bthe daughter of\b/i.test(text) || /\bShe married\b/i.test(text) || /^\s*Gender:\s*Female/im.test(text)) {
        vitals.gender = 'Female';
      } else if (/\bson of\b/i.test(text) || /\bhe married\b/i.test(text)) {
        vitals.gender = 'Male';
      } else if (/\bdaughter of\b/i.test(text) || /\bshe married\b/i.test(text)) {
        vitals.gender = 'Female';
      }
    }

    if (!vitals.marriageDate) {
      const marriageMatch = text.match(/married[^\n]+?\bon\s+([A-Za-z]+\s+\d+,\s+\d{4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+[A-Za-z]+\s+\d{4})(?:,\s+in\s+([^\n.<]+?))?(?:\.|$|<)/i);
      if (marriageMatch) {
        vitals.marriageDate = formatDateToISO(marriageMatch[1]);
        if (marriageMatch[2] && !vitals.marriageLocation) {
          vitals.marriageLocation = marriageMatch[2].replace(/\.$/, '').trim();
        }
      }
    }

    if (!vitals.spouseName) {
      const spouseMatch = text.match(/married\s+(?:\d+-year-old\s+)?(?:\[\[[^|]*\|([^\]]+)\]\]|'''([^']+)'''|([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+))/i);
      if (spouseMatch) {
        vitals.spouseName = (spouseMatch[1] || spouseMatch[2] || spouseMatch[3]).trim();
      }
    }

    if (!vitals.marriageEndDate) {
      const divorceMatch = text.match(/(?:marriage ended in divorce|divorced)\s+on\s+([^,.\n]+)/i);
      if (divorceMatch) {
        vitals.marriageEndDate = divorceMatch[1].trim();
      }
    }

    // Sanitize Dutch tussenvoegsels (van, de, van der, etc.) placed inside firstName
    vitals = sanitizeDutchNamePrefixes(vitals);

    // Save to localStorage for cross-tab extension sync
    try {
      localStorage.setItem('lineage_nexus_pending_bio', content);
      localStorage.setItem('lineage_nexus_pending_vitals', JSON.stringify(vitals));
    } catch (e) {}

    // Embed structured metadata comment if missing
    const cleanBio = content.replace(/<!--\s*LINEAGE_NEXUS_DATA:[\s\S]+?-->/, '').trim();
    const payloadWithMeta = cleanBio + '\n\n<!-- LINEAGE_NEXUS_DATA: ' + JSON.stringify(vitals) + ' -->';

    navigator.clipboard.writeText(payloadWithMeta);
    window.postMessage({ type: 'LINEAGE_NEXUS_PUSH_BIO', biography: cleanBio, vitals }, '*');
    setPushed(true);
    setTimeout(() => setPushed(false), 2500);
  };
  
  if (!inline && (match || content.includes('\n'))) {
    const language = match ? match[1] : '';
    // The wikitext biography is the artefact this whole product exists to
    // produce, so it carries the brand's gold. Everything else stays neutral —
    // gold means "finished, sourced, ready to publish", not "code".
    const isBiography = language === 'wiki';
    const displayContent = content.replace(/<!--\s*LINEAGE_NEXUS_DATA:[\s\S]+?-->/, '').trim();

    return (
      <div className={`relative group/code rounded-xl border bg-card overflow-hidden my-6 shadow-sm ${
        isBiography ? 'border-highlight/40' : 'border-border/50'
      }`}>
        <div className={`flex items-center justify-between px-4 py-2.5 border-b ${
          isBiography ? 'bg-highlight-soft border-highlight/30' : 'bg-muted/30 border-border/50'
        }`}>
          <span className={`text-[10px] font-bold uppercase tracking-widest ${
            isBiography ? 'text-highlight' : 'text-secondary/60'
          }`}>
            {isBiography ? 'WikiTree biography' : (language || 'Code')}
          </span>
          <div className="flex items-center gap-4">
            {isBiography && (
              <button
                onClick={handlePushExtension}
                className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest text-highlight hover:opacity-80 transition-opacity focus:outline-none cursor-pointer"
                title="Push biography directly to WikiTree Extension"
              >
                {pushed ? (
                  <>
                    <Check size={12} className="text-green-500" />
                    <span className="text-green-500">Pushed to Extension</span>
                  </>
                ) : (
                  <>
                    <Sparkles size={12} className="text-highlight" />
                    <span>Send to Extension</span>
                  </>
                )}
              </button>
            )}
            <button
              onClick={() => {
                navigator.clipboard.writeText(displayContent);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }}
              className={`flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest transition-colors focus:outline-none cursor-pointer ${
                isBiography ? 'text-highlight/70 hover:text-highlight' : 'text-secondary/40 hover:text-accent'
              }`}
            >
              {copied ? (
                <>
                  <Check size={12} className="text-green-500" />
                  <span className="text-green-500">Copied</span>
                </>
              ) : (
                <>
                  <Copy size={12} />
                  <span>Copy</span>
                </>
              )}
            </button>
          </div>
        </div>
        {/* text-primary is explicit, not inherited: this block also renders inside
            user bubbles, whose foreground is the on-accent colour. Inheriting it
            would put dark navy text on the dark card background. */}
        <pre className="p-5 font-mono text-xs overflow-x-auto leading-relaxed text-primary">
          <code className={className} {...props}>
            {displayContent}
          </code>
        </pre>
      </div>
    );
  }

  // Same reasoning: a muted surface with the standard foreground reads correctly
  // on the page and on an accent-filled bubble. Accent-on-accent did not.
  return (
    <code className="bg-muted text-primary px-1.5 py-0.5 rounded font-mono text-[0.9em] border border-border" {...props}>
      {children}
    </code>
  );
};

const ErrorMessageCard = ({ msg, onRetry, lastUserQuery }) => {
  const content = msg.content || '';
  
  let mainSummary = content;
  let researchLogsText = '';
  let technicalDetailText = '';

  if (content.includes('Interrupted Research Log:')) {
    const parts = content.split(/Interrupted Research Log:|Attempted Steps:/i);
    mainSummary = parts[0].trim();
    researchLogsText = parts[1] ? parts[1].trim() : '';
  } else if (content.includes('Attempted Steps:')) {
    const parts = content.split('Attempted Steps:');
    mainSummary = parts[0].trim();
    researchLogsText = parts[1] ? parts[1].trim() : '';
  }

  // Clean dangling markdown formatting remnants
  mainSummary = mainSummary.replace(/\*\*$/, '').replace(/^\*\*/, '').trim();

  let userFriendlyText = mainSummary;
  if (mainSummary.includes('500') || mainSummary.includes('INTERNAL') || mainSummary.includes('Internal error')) {
    userFriendlyText = 'An unexpected internal error occurred with the AI service. This is usually temporary — please try clicking Retry to resume.';
    technicalDetailText = mainSummary;
  } else if (mainSummary.includes('503') || mainSummary.includes('UNAVAILABLE')) {
    userFriendlyText = 'The model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again in a few moments.';
    technicalDetailText = mainSummary;
  } else if (mainSummary.includes('429') || mainSummary.includes('RESOURCE_EXHAUSTED') || mainSummary.includes('Quota exceeded')) {
    userFriendlyText = 'Gemini API Quota Exceeded. You have reached the rate limit for free-tier requests. Please wait ~1 minute before retrying.';
    technicalDetailText = mainSummary;
  } else if (mainSummary.includes("{'error':") || mainSummary.includes('{"error":') || mainSummary.includes('Traceback')) {
    userFriendlyText = 'Research was interrupted due to a backend service error. Expand technical details below for the full log.';
    technicalDetailText = mainSummary;
  }

  return (
    <div className="p-5 bg-red-950/20 border border-red-500/25 rounded-xl shadow-lg animate-in fade-in slide-in-from-bottom-2">
      <div className="flex items-start gap-3.5">
        <div className="w-8 h-8 rounded-lg bg-red-500/15 border border-red-500/30 flex items-center justify-center shrink-0 mt-0.5">
          <AlertCircle size={18} className="text-red-400" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between gap-3 mb-1.5">
            <h4 className="text-xs font-bold uppercase tracking-wider text-red-300">
              Research Interrupted
            </h4>
            {msg.retry && (
              <button
                onClick={() => onRetry && lastUserQuery && onRetry(lastUserQuery)}
                className="flex items-center gap-1.5 px-3 py-1 bg-red-600/80 hover:bg-red-600 text-white rounded-lg text-xs font-semibold shadow-sm transition-all cursor-pointer hover:shadow-red-900/30"
              >
                <RotateCcw size={12} />
                <span>Retry</span>
              </button>
            )}
          </div>

          <p className="text-sm text-red-100/90 leading-relaxed font-medium mb-3">
            {userFriendlyText}
          </p>

          {(technicalDetailText || researchLogsText) && (
            <details className="group mt-2 border border-red-500/20 rounded-lg bg-black/40 overflow-hidden">
              <summary className="px-3 py-2 text-xs font-mono text-red-300/80 hover:text-red-200 cursor-pointer flex items-center justify-between select-none group-open:bg-red-950/40 border-b border-transparent group-open:border-red-500/20 transition-colors">
                <span className="font-semibold">Show Technical Details & Debug Log</span>
                <ChevronDown size={14} className="group-open:rotate-180 transition-transform text-red-400" />
              </summary>
              <div className="p-3 text-xs font-mono text-rose-200/70 space-y-3 max-h-60 overflow-y-auto">
                {technicalDetailText && (
                  <div>
                    <div className="text-[10px] uppercase font-bold text-red-400/80 mb-1">Error Code / Payload</div>
                    <pre className="p-2.5 bg-black/50 rounded border border-red-900/30 whitespace-pre-wrap break-all text-[11px] text-red-200/90">
                      {technicalDetailText}
                    </pre>
                  </div>
                )}
                {researchLogsText && (
                  <div>
                    <div className="text-[10px] uppercase font-bold text-red-400/80 mb-1">Interrupted Research Steps</div>
                    <div className="p-2.5 bg-black/50 rounded border border-red-900/30 text-[11px] markdown-content text-rose-200/90">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {researchLogsText}
                      </ReactMarkdown>
                    </div>
                  </div>
                )}
              </div>
            </details>
          )}
        </div>
      </div>
    </div>
  );
};

const ChatInterface = ({ messages, isLoading, status, onRetry }) => {
  const [copiedIdx, setCopiedIdx] = useState(null);
  const [visibleCount, setVisibleCount] = useState(INITIAL_VISIBLE_COUNT);

  // Auto-reset when messages array resets
  useEffect(() => {
    if (messages.length <= INITIAL_VISIBLE_COUNT) {
      setVisibleCount(INITIAL_VISIBLE_COUNT);
    }
  }, [messages.length]);

  const handleCopy = (text, idx) => {
    navigator.clipboard.writeText(text);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  if (messages.length === 0) return null;

  const totalMessages = messages.length;
  const hiddenCount = Math.max(0, totalMessages - visibleCount);
  const displayedMessages = hiddenCount > 0 ? messages.slice(hiddenCount) : messages;

  const handleLoadEarlier = () => {
    setVisibleCount((prev) => prev + PAGE_INCREMENT);
  };

  const lastUserQuery = [...messages].reverse().find(m => m.role === 'user')?.content;

  return (
    <section className="bg-surface section-divider">
      <div className="container" style={{ maxWidth: '800px' }}>
        {/* Paginated Trimming: Load Earlier Messages Banner */}
        {hiddenCount > 0 && (
          <div className="flex justify-center mb-6">
            <button
              onClick={handleLoadEarlier}
              className="flex items-center gap-2 px-4 py-2 bg-card border border-border/80 rounded-full text-xs font-semibold text-secondary/80 hover:text-primary hover:border-accent shadow-sm transition-all cursor-pointer group"
            >
              <History size={14} className="group-hover:rotate-[-45deg] transition-transform" />
              <span>Load earlier messages</span>
              <span className="bg-muted px-2 py-0.5 rounded-full text-[10px] font-mono text-secondary">
                {hiddenCount} remaining
              </span>
            </button>
          </div>
        )}

        <div className="flex flex-col gap-8">
          {displayedMessages.map((msg, idx) => {
            const realIdx = hiddenCount + idx;
            if (msg.role === 'error') {
              return (
                <ErrorMessageCard
                  key={realIdx}
                  msg={msg}
                  onRetry={onRetry}
                  lastUserQuery={lastUserQuery}
                />
              );
            }

            return (
              <div
                key={realIdx}
                className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'} animate-in fade-in slide-in-from-bottom-2 duration-300 group`}
              >
                <div className="w-full flex items-center justify-between mb-2 px-1 opacity-40 select-none">
                  <div className="flex items-center gap-2">
                    {msg.role !== 'user' && (
                      <>
                        <Network size={12} />
                        <span className="text-[10px] font-bold uppercase tracking-widest">Lineage Nexus</span>
                      </>
                    )}
                  </div>
                  
                  {msg.role !== 'user' && (
                    <button 
                      onClick={() => handleCopy(msg.content, realIdx)}
                      className="opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1.5 hover:text-accent"
                    >
                      {copiedIdx === realIdx ? <Check size={10} /> : <Copy size={10} />}
                      <span className="text-[9px] font-bold uppercase tracking-tighter">
                        {copiedIdx === realIdx ? 'Copied' : 'Copy'}
                      </span>
                    </button>
                  )}
                </div>

                <div
                  className={`relative transition-all ${msg.role === 'user'
                    ? 'bg-accent text-on-accent px-6 py-4 rounded-2xl shadow-sm border-accent shadow-accent/10 rounded-tr-none ml-auto max-w-[85%]'
                    : 'w-full pt-2'
                    }`}
                >
                  <div className={`space-y-4 markdown-content ${msg.role === 'user'
                    ? 'text-sm leading-relaxed text-on-accent'
                    : 'text-primary/95 agent-prose'}`}>
                    <ReactMarkdown
                      remarkPlugins={[remarkGfm]}
                      components={{
                        code: CodeBlock,
                        // react-markdown wraps fenced code in its own <pre>. Since
                        // CodeBlock renders a full <div> chrome, that nesting puts a
                        // block element inside <pre> (invalid) and applies
                        // white-space: pre to the wrapper. Pass through instead.
                        pre: ({ children }) => <>{children}</>,
                        table: ({ node, ...props }) => (
                          <div className="overflow-x-auto my-6 border border-border rounded-xl">
                            <table className="w-full text-left border-collapse" {...props} />
                          </div>
                        ),
                        thead: ({ node, ...props }) => <thead className="bg-card border-b border-border" {...props} />,
                        th: ({ node, ...props }) => <th className="px-4 py-3 text-[10px] font-bold uppercase tracking-widest text-secondary/60" {...props} />,
                        td: ({ node, ...props }) => <td className="px-4 py-3 border-b border-border/50 text-xs" {...props} />,
                        h1: ({ node, ...props }) => <h1 className="text-lg font-bold text-primary mb-4 mt-8" {...props} />,
                        h2: ({ node, ...props }) => <h2 className="text-base font-bold text-primary mb-3 mt-6" {...props} />,
                        h3: ({ node, ...props }) => <h3 className="text-sm font-bold text-primary mb-2 mt-4" {...props} />,
                        strong: ({ node, ...props }) => <strong className="font-bold text-primary/90" {...props} />,
                        a: ({ node, ...props }) => (
                          <a
                            className={`${msg.role === 'user' ? 'text-on-accent underline font-bold' : 'text-accent'} underline underline-offset-4 hover:opacity-80 transition-opacity`}
                            target="_blank"
                            rel="noopener noreferrer"
                            {...props}
                          />
                        ),
                        ul: ({ node, ...props }) => <ul className="list-disc pl-5 space-y-2 my-4" {...props} />,
                        ol: ({ node, ...props }) => <ol className="list-decimal pl-5 space-y-2 my-4" {...props} />,
                        li: ({ node, ...props }) => <li className="pl-1" {...props} />,
                      }}
                    >
                      {(msg.content || '').replace(/<!--\s*LINEAGE_NEXUS_DATA:[\s\S]+?-->/gi, '').trim()}
                    </ReactMarkdown>
                  </div>
                </div>
              </div>
            );
          })}

          {isLoading && (
            <div className="flex flex-col items-start mb-8 animate-in fade-in slide-in-from-bottom-2">
              <div className="bg-card border border-border px-6 py-4 rounded-2xl rounded-tl-none shadow-sm flex items-center gap-4">
                <div className="flex gap-1.5 h-4 items-center">
                  <span className="w-1.5 h-1.5 bg-accent rounded-full animate-bounce" style={{ animationDelay: '0s' }}></span>
                  <span className="w-1.5 h-1.5 bg-accent rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></span>
                  <span className="w-1.5 h-1.5 bg-accent rounded-full animate-bounce" style={{ animationDelay: '0.4s' }}></span>
                </div>
                <span className="text-[11px] font-bold uppercase tracking-[0.2em] text-secondary/60">
                  {status || 'Connecting to archives…'}
                </span>
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
};

export default ChatInterface;
